const prompts = [
  { text: "What's an ordinary place that feels extraordinary to you because of what happened there?" },
  { text: "What's an instinct you've learned to trust?" },
  { text: "What's an experience from growing up when you realized your parents didn't have all the answers?" },
  { text: "When is the first time you remember feeling proud of yourself?" },
  { text: "What's a smell that brings back a vivid memory for you?" },
  { text: "Who is someone who played an important role in your life, but you haven't communicated with them in years?" },
  { text: "What is something about your hometown you've come to appreciate over time?" },
  { text: "What's a moment from your childhood when you realized you wanted to make different choices than your parents?" },
  { text: "What was your form of rebellion as a teenager?" },
  { text: "What do you admire about your teenage self?" },
  { text: "Where would you go to feel safe as a kid?" },
  { text: "Were you ever obsessed with a particular cosmic question as a kid?" },
  { text: "What's something you thought was normal about your childhood that you now realize was unusual?" },
  { text: "Growing up, was there a peer who you modeled your behavior after, for better or for worse?" },
  { text: "What's something a parent of yours taught you to appreciate?" },
  { text: "What's a place that shaped you as much as any person did?" },
  { text: "What was the most significant year in your life if you can think about it that way?" },
  { text: "When you were bored as a kid, where would your imagination take you?" },
  { text: "What do you think childhood is for?" },
  { text: "What's something about the place you grew up in that felt confining to you?" },
  { text: "What's a moment when a stranger made you feel loved?" },
  { text: "What is something you think about very differently today than you did 10 years ago?" },
  { text: "How comfortable are you with silence?" },
  { text: "What's a lesson you have to keep learning over and over?" },
  { text: "What's something you changed your mind about recently?" },
  { text: "What's a goal you're glad you gave up on?" },
  { text: "When do you feel most like an outsider?" },
  { text: "When's the last time you forgave yourself for something?" },
  { text: "What is proof that somebody really knows you?" },
  { text: "What feels unreachable to you right now?" },
  { text: "What's a quality you're drawn to that you don't possess?" },
  { text: "In what ways do you think you get in your own way?" },
  { text: "What's a contradiction about yourself you've had to come to terms with?" },
  { text: "What have you learned to be careful about?" },
  { text: "What's an expression of love you're trying to get better at?" },
  { text: "What have you learned to take less seriously?" },
  { text: "What's a rejection that you're grateful for in retrospect?" },
  { text: "What emotion do you understand better than all the others?" },
  { text: "What's a hard truth you've had to learn about yourself?" },
  { text: "What makes you irrationally defensive?" },
  { text: "How do you cope with regret?" },
  { text: "In what ways do you think happiness is a choice?" },
  { text: "Has your idea of success changed over time?" },
  { text: "What is something you think you still have to prove to people you meet?" },
  { text: "What is something people think comes naturally to you, but actually, it takes a lot of work?" },
  { text: "What's something people praise you for that doesn't feel like a compliment?" },
  { text: "Is there anything in your life that has felt predestined?" },
  { text: "Do you have a belief system that helps you make sense of the world?" },
  { text: "How do you stay connected to people you've lost?" },
  { text: "Has your idea of what it means to be a good person changed?" },
  { text: "Have you ever had a premonition about something that came true?" },
  { text: "Do you think there's more to reality than we can see or touch?" },
  { text: "If you could design the afterlife, what would it look like?" },
  { text: "Where have you experienced awe recently?" },
  { text: "Does the idea of an infinite universe excite you or scare you?" },
  { text: "Do you think about the legacy you will leave behind?" },
  { text: "What's your best defense against despair?" },
  { text: "Was there a bedrock truth in your life that you found out wasn't true?" },
  { text: "How often do you think about death?" },
  { text: "What is a place you consider sacred?" },
  { text: "Is there anything you think you got away with, that you shouldn't have?" },
  { text: "What's an unexpected act of generosity you've experienced recently?" },
  { text: "Are you comfortable with being forgotten?" },
  { text: "How has your idea of what it means to live a good life changed?" },
  { text: "Do you think people can really change?" }
];
